#!/bin/bash

qemu-system-x86_64 \
    -m 8G \
    -smp cpus=2 \
    -monitor stdio \
    -cpu core2duo \
    -machine type=q35,accel=hvf \
    -netdev user,id=mynet0,hostfwd=tcp::22222-:22 \
    -device virtio-net-pci,netdev=mynet0 \
    -device qemu-xhci \
    -hda ./lfs_bios_legacy.iso