#!/bin/bash

qemu-system-x86_64 \
    -m 8G \
    -smp 2 \
    -cpu core2duo \
    -monitor stdio \
    -machine type=q35,accel=hvf \
    -netdev user,id=mynet0,hostfwd=tcp::2222-:22 \
    -device virtio-net-pci,netdev=mynet0 \
    -device qemu-xhci \
    -vga virtio \
    -hda ./debian.qcow2 \
    -hdb ./UEFI.qcow2 \
    -drive if=pflash,format=raw,readonly=on,file=/Users/xtem/Desktop/edk2/Build/OvmfX64/DEBUG_GCC5/FV/OVMF_CODE.fd \
    -drive if=pflash,format=raw,file=/Users/xtem/Desktop/edk2/Build/OvmfX64/DEBUG_GCC5/FV/OVMF_VARS.fd 
